# Input file for tmm.py. Define source, superstrate, substrate and as many layers as you want in between them. 

# wavelength is in free space
# te and tm amplitudes are complex numbers represented by list; they are renormalised inside the code to ensure a total amplitude of 1
# epsilon and mu are relative permeability and permittivity
# thickness is defined in the same units as wavelength

[source]
wavelength = 6.2831853
theta = 57
phi = 23
te_amplitude = [1, 0]
tm_amplitude = [0, 1]

[superstrate]
epsilon = 1.4
mu = 1.2

[[layer]]
epsilon = 2
mu = 1
thickness = 1.57079

[[layer]]
epsilon = 1
mu = 3
thickness = 3.14159

[substrate]
epsilon = 1.8
mu = 1.6
